### ISSUE TITLE
"Error starting app!" message for Shiny Express examples

### ISSUE THREAD

**Issue by mfebrizio** [posit-dev/py-shiny-site#181]
At least two examples in the Shiny Express docs seem to be broken and are showing the following error message:

```
Traceback (most recent call last):
  File "<exec>", line 384, in _start_app
  File "<exec>", line 357, in __init__
  File "/lib/python3.12/site-packages/shiny/express/_run.py", line 62, in wrap_express_app
    app_module = importlib.import_module(package_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/lib/python3.12/site-packages/shiny/express/_run.py", line 102, in exec_module
    module.app = create_express_app(  # pyright: ignore[reportAttributeAccessIssue]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/shiny/express/_run.py", line 132, in create_express_app
    app_ui = run_express(file, package_name).tagify()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/shiny/express/_run.py", line 220, in run_express
    exec(
  File "/home/pyodide/app_t9jwvn5ng0beenxubec5/app.py", line 1, in <module>
    from icons import question_circle_fill
ModuleNotFoundError: No module named 'icons'
```

Looks like whatever environment is running the examples is missing a dependency?

Examples checked:
- [express.ui.tooltip](https://shiny.posit.co/py/api/express/express.ui.tooltip.html)
- [express.ui.popover](https://shiny.posit.co/py/api/express/express.ui.popover.html)

**Comment by phobson** [comment]
Also [value_box](https://shiny.posit.co/py/api/core/ui.value_box.html#examples)

Previously the examples had a second icons.py file included as a part of the example.

**Comment by gadenbuie** [comment]
Thanks for the report! We have an issue upstream in py-shiny (where the fix needs to be) that's tracking this.

**Comment by gadenbuie** [comment]
It turns out the issue is probably happening in this repo after all. I can't reproduce the issue locally (note that we're using Python 3.10 in the GHA workflow that builds the docs) and the problem doesn't appear in our dev docs build.

In investigating, I noticed that if you [view the page source for the value box example](view-source:https://shiny.posit.co/py/api/core/ui.value_box.html%23examples) for the release docs, you can see that the supporting `icons.py` file isn't included in the shinylive chunk.

**Comment by gadenbuie** [comment]
More investigation:

* https://6697d5703d3ccfd3aee21bef--pyshiny.netlify.app/api/core/ui.value_box.html has the supporting file ([commit](https://github.com/posit-dev/py-shiny-site/commit/c763e6be7001f895dc42b7cebeb421785393fcbc), [GHA run](https://github.com/posit-dev/py-shiny-site/actions/runs/9975779991/job/27566382029))
* https://669988109dd1e06850104ad4--pyshiny.netlify.app/api/core/ui.value_box.html does not  ([commit](https://github.com/posit-dev/py-shiny-site/commit/ea2d54082d42ab11b346e024a8c7b17b823aaab3), [GHA run](https://github.com/posit-dev/py-shiny-site/actions/runs/9998571239/job/27637767817))

So something changed with the rc-v1.0.0 commit

**Comment by wch** [comment]
Just adding on to the rc-v1.0.0 observation:

- The icons.py file was included in the PR just before the 1.0.0 PR:
  -  #166
  - https://pr-166--pyshiny.netlify.app/api/core/ui.value_box.html#examples

- The icons.py was not present in the 1.0.0 PR:
  - #167
  - https://pr-166--pyshiny.netlify.app/api/core/ui.value_box.html#examples

**Comment by wch** [comment]
Looking through the deployments for each commit in #167, it appears that:

- The first commit that shows the problem is f87ea2aca27647e232e3ef1e71aa043293223da6.
- From the [GHA logs](https://github.com/posit-dev/py-shiny-site/actions/runs/9975087614/job/27563993890), we can find that it's deployed at https://6697cb511b075ac6f6af3e8e--pyshiny.netlify.app/api/core/ui.value_box.html

**Comment by wch** [comment]
@gadenbuie: @schloerke and I did some investigating, and we think it's likely that the issue is due to these commits:

- 83647e2126306caa7ca8f7bcd6dc98a04374e1aa
- f4039e2b9775d8f11628db555a844b21bd7af65d

When the site is built, it uses a venv and installs py-shiny to it, so that statement would evaluate to `is_support_file=False` for all files.

Note that when the docs are built from py-shiny main, it does not use a venv, so in that case it would have `is_support_file=True`.

@schloerke is working on a PR to use a `pip install -e` for py-shiny, so in that case it would not be in the `venv/` directory. But that could be a bit fragile because if we later decide to install shiny the regular way, then this problem would surface again.

Why do we need to avoid venv directories for support files? Can we remove that logic?

**Comment by gadenbuie** [comment]
> When the site is built, it uses a venv and installs py-shiny to it, so that statement would evaluate to `is_support_file=False` for all files.

Ah that makes sense!

> Why do we need to avoid venv directories for support files? Can we remove that logic?

During development I've used a local `.venv` inside the `api-examples` folder to test an example with dev versions of other packages. That's more of a "me" problem than an everyone problem, but I think it's worth taking into account.

I think the updated logic would look at the path parts relative to the `api-examples` folder and not in the absolute path parts.
