### ISSUE TITLE
"?_gl" analytics tracking is breaking (404) a link in deployment page. Link: "comparison of Posit’s hosting and deployment options for Shiny"

### ISSUE THREAD

**Issue by drpawelo** [posit-dev/py-shiny-site#214]
in the page [https://shiny.posit.co/py/docs/deploy.html](https://shiny.posit.co/py/docs/deploy.html)
link under words "comparison of Posit’s hosting and deployment options for Shiny"
should probably point to [https://posit.co/products/open-source/shiny-server/](https://posit.co/products/open-source/shiny-server/)
but instead is passing an analytics parameter, which somehow greaks the url.
Broken Url looks like this:
"https://posit.co/products/open-source/shinyserver/?_gl=1*19l3z8y*_ga*MjEzMjMxNTM4NC4xNzI0MjYwMTI0*_ga_8QJS108GF1*MTcyNjQ0NjExNC4yNi4xLjE3MjY0NDY1MDAuMC4wLjA.*_ga_2C0WZ1JHG0*MTcyNjQ0NjExNC4zNi4xLjE3MjY0NDY1MDAuMC4wLjA."

I checked on chrome and safari on mac, and on chrome on iphone, on wifi and on 3g mobile internet.

**Comment by gadenbuie** [comment]
Confusingly, the link is correct in the source: https://github.com/posit-dev/py-shiny-site/blob/28cd058deed1bb654e6c3fcce86c4e294e2963af/docs/deploy.qmd#L37

@gregswinehart Could this be a Google Analytics configuration issue?

**Comment by gregswinehart** [comment]
Checking it out!

**Comment by awilliams1275** [comment]
The HREF for the URL on https://shiny.posit.co/py/docs/deploy.html needs to change:

FROM: https://posit.co/products/open-source/shinyserver/

TO:     https://posit.co/products/open-source/shiny-server/    (Add a hypen between "shiny" and "server")


And then the following URL will return a 200 OK:
https://posit.co/products/open-source/shiny-server/?_gl=1*gj2smr*_ga*ODgyOTk2MTI1LjE3MjQ4NTcwMjE.*_ga_8QJS108GF1*MTcyNjUyNjEyNC4yOS4wLjE3MjY1MjYxMjguMC4wLjA.*_ga_2C0WZ1JHG0*MTcyNjUyNjEyNC4yMS4xLjE3MjY1MjY5NzYuMC4wLjA.

**Comment by awilliams1275** [comment]
Hey Greg, no need to change the HREF on https://shiny.posit.co/py/docs/deploy.html; I believe that the issue is now resolved.

For the https://posit.co/products/open-source/shinyserver/ URL, WordPress contained a redirect for "shinyserver" to "shiny-server", which returns a 200 if the URL does not have a query string. I adjusted the redirect parameters for the URL to accommodate the query string, and the URL should now work as expected:

https://posit.co/products/open-source/shinyserver/?_gl=1*1bafw85*_ga*ODgyOTk2MTI1LjE3MjQ4NTcwMjE.*_ga_2C0WZ1JHG0*MTcyNjUyNjEyNC4yMS4xLjE3MjY1Mjg2ODUuMC4wLjA.*_ga_8QJS108GF1*MTcyNjUyODMyNS4zMC4xLjE3MjY1Mjg0MjYuMC4wLjA.

**Comment by gregswinehart** [comment]
Thank you so much @awilliams1275 !

**Comment by gregswinehart** [comment]
Also, thank you @drpawelo and @gadenbuie.  Really appreciate your time on this.
